name: PermWeather
version: 1.5
author: Edvin Flodin
main: com.codepentry.redpixl.permweather.PermWeather
api-version: 1.15
commands:
  permday:
    description: Set a permanent day
    usage: /permday <enable:disable>
  permnight:
    description: Set a permanent night
    usage: /permnight <enable:disable>
  lobby2:
    description: Go to the lobby
    usage: /lobby2
  permweather:
    description: Permweather help
    usage: /permweather <help/enabled>
  permrain:
    description: Make it rain infinitly
    usage: /permrain <enable:disable>


